var SentenceData = {
  "lesson": 54,
  "text": "阿女含涙答\n蘭芝初還時\n府吏見丁寜\n結誓不别離\n今日違情義\n恐此事非奇\n自可斷來信\n徐徐更謂之\n阿母白媒人\n貧賤有此女\n始適還家門\n不堪吏人婦\n豈合令郎君\n幸可廣問訊\n不得便相許\n媒人去數日\n尋遣丞請還\n説有蘭家女\n承籍有宦官\n云有第五郎\n蘭芝仰頭答\n理實如兄言\n謝家事夫婿\n中道還兄門\n處分適兄意\n那得自任專\n雖與府吏要\n渠會永無緣\n矯逸未有婚\n遣丞為媒人\n主簿通語言\n直説太守家\n有此令郎君\n既欲結大義\n故遣來貴門\n阿母謝媒人\n女子先有誓\n老姥豈敢言\n阿兄得聞之\n悵然心中煩\n舉言謂阿妹\n作計何不量\n先嫁得府吏\n後嫁得郎君\n否泰如天地\n足以榮汝身\n不嫁異郎體\n其往欲何云\n登即相許和\n便可作婚婣\n媒人下床去\n諾諾複爾爾\n還部白府君\n下官奉使命\n言談大有緣",
  "sentences": [
    { "number": 1, "original": "阿女含涙答", "transliteration": "", "translation": "Но со слезами ей сказала дочь:" },
    { "number": 2, "original": "蘭芝初還時", "transliteration": "", "translation": "«Ланьчжи домой недавно так вернулась!" },
    { "number": 3, "original": "府吏見丁寜", "transliteration": "", "translation": "Чиновник при прощанье приказал," },
    { "number": 4, "original": "結誓不别離", "transliteration": "", "translation": "И я сама клялась не разлучаться." },
    { "number": 5, "original": "今日違情義", "transliteration": "", "translation": "Я не нарушу верности ему." },
    { "number": 6, "original": "恐此事非奇", "transliteration": "", "translation": "Согласье дать — поступок недостойный." },
    { "number": 7, "original": "自可斷來信", "transliteration": "", "translation": "Я свату дам решительный отказ," },
    { "number": 8, "original": "徐徐更謂之", "transliteration": "", "translation": "Скажу, что рано говорить об этом»." },
    { "number": 9, "original": "阿母白媒人", "transliteration": "", "translation": "И свату вежливо сказала мать:" },
    { "number": 10, "original": "貧賤有此女", "transliteration": "", "translation": "«Нет, дочь моя бедна и недостойна," },
    { "number": 11, "original": "始適還家門", "transliteration": "", "translation": "И первый муж ее вернул домой." },
    { "number": 12, "original": "不堪吏人婦", "transliteration": "", "translation": "Для мелкого чиновника не пара —" },
    { "number": 13, "original": "豈合令郎君", "transliteration": "", "translation": "Вельможи сыну разве подойдет?»" },
    { "number": 14, "original": "幸可廣問訊", "transliteration": "", "translation": "Проходят дни с тех пор, как сват ушел," },
    { "number": 15, "original": "不得便相許", "transliteration": "", "translation": "И я, старуха, не берусь решать»." },
    { "number": 16, "original": "媒人去數日", "transliteration": "", "translation": "Проходят дни с тех пор, как сват ушел," },
    { "number": 17, "original": "尋遣丞請還", "transliteration": "", "translation": "Начальник округа его шлет снова" },
    { "number": 18, "original": "説有蘭家女", "transliteration": "", "translation": "Явился снова сват в семейство Лю:" },
    { "number": 19, "original": "承籍有宦官", "transliteration": "", "translation": "А этот — сын высокого вельможи:" },
    { "number": 20, "original": "云有第五郎", "transliteration": "", "translation": "Сказать, что пятый сын его красив," },
    { "number": 21, "original": "蘭芝仰頭答", "transliteration": "", "translation": "Ему Ланьчжи покорно отвечала:" },
    { "number": 22, "original": "理實如兄言", "transliteration": "", "translation": "«Брат справедливо говорит своей сестре." },
    { "number": 23, "original": "謝家事夫婿", "transliteration": "", "translation": "Я, мужа прежнего семью оставив," },
    { "number": 24, "original": "中道還兄門", "transliteration": "", "translation": "Как долг велит, пришла в свой отчий дом" },
    { "number": 25, "original": "處分適兄意", "transliteration": "", "translation": "И поступать должна, как брат прикажет," },
    { "number": 26, "original": "那得自任專", "transliteration": "", "translation": "И не осмелюсь самовольной быть." },
    { "number": 27, "original": "雖與府吏要", "transliteration": "", "translation": "Хотя чиновнику дала я клятву," },
    { "number": 28, "original": "渠會永無緣", "transliteration": "", "translation": "Но, может, нам не суждено сойтись," },
    { "number": 29, "original": "矯逸未有婚", "transliteration": "", "translation": "Но до сих пор супруги не имеет." },
    { "number": 30, "original": "遣丞為媒人", "transliteration": "", "translation": "Явился снова сват в семейство Лю:" },
    { "number": 31, "original": "主簿通語言", "transliteration": "", "translation": "И вот меня послал к воротам вашим»." },
    { "number": 32, "original": "直説太守家", "transliteration": "", "translation": "«В семье правителя есть сын-красавец," },
    { "number": 33, "original": "有此令郎君", "transliteration": "", "translation": "А этот — сын высокого вельможи:" },
    { "number": 34, "original": "既欲結大義", "transliteration": "", "translation": "Хотел бы важный совершить обряд" },
    { "number": 35, "original": "故遣來貴門", "transliteration": "", "translation": "И вот меня послал к воротам вашим»." },
    { "number": 36, "original": "阿母謝媒人", "transliteration": "", "translation": "Посланцу скромно отвечала мать:" },
    { "number": 37, "original": "女子先有誓", "transliteration": "", "translation": "«Дочь клятвою себя связала с мужем," },
    { "number": 38, "original": "老姥豈敢言", "transliteration": "", "translation": "И я, старуха, не берусь решать»." },
    { "number": 39, "original": "阿兄得聞之", "transliteration": "", "translation": "С досадой горькой брат Ланьчжи вмешался" },
    { "number": 40, "original": "悵然心中煩", "transliteration": "", "translation": "С досадой горькой брат Ланьчжи вмешался" },
    { "number": 41, "original": "舉言謂阿妹", "transliteration": "", "translation": "И, обратясь к своей сестре, сказал:" },
    { "number": 42, "original": "作計何不量", "transliteration": "", "translation": "«Не будь в своих решеньях безрассудной:" },
    { "number": 43, "original": "先嫁得府吏", "transliteration": "", "translation": "Чиновником незнатным был твой муж," },
    { "number": 44, "original": "後嫁得郎君", "transliteration": "", "translation": "А этот — сын высокого вельможи:" },
    { "number": 45, "original": "否泰如天地", "transliteration": "", "translation": "Как небо и земля, они различны." },
    { "number": 46, "original": "足以榮汝身", "transliteration": "", "translation": "Знай, с новым мужем слава ждет тебя," },
    { "number": 47, "original": "不嫁異郎體", "transliteration": "", "translation": "Ты упускаешь знатного супруга." },
    { "number": 48, "original": "其往欲何云", "transliteration": "", "translation": "Скажи, чего же ждешь и хочешь ты?»" },
    { "number": 49, "original": "登即相許和", "transliteration": "", "translation": "И я согласна в новый брак вступить»." },
    { "number": 50, "original": "便可作婚婣", "transliteration": "", "translation": "И, соглашенье снова подтвердив," },
    { "number": 51, "original": "媒人下床去", "transliteration": "", "translation": "Встает поспешно с места сват довольный" },
    { "number": 52, "original": "諾諾複爾爾", "transliteration": "", "translation": "И, соглашенье снова подтвердив," },
    { "number": 53, "original": "還部白府君", "transliteration": "", "translation": "К правителю торопится с отчетом:" },
    { "number": 54, "original": "下官奉使命", "transliteration": "", "translation": "«Я, недостойный, выполнил приказ." },
    { "number": 55, "original": "言談大有緣", "transliteration": "", "translation": "К вступленью в брак судьба благоприятна»." }
  ]
};